name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.10.0'

    - name: Install Dependencies
      run: |
        npm install
      working-directory: ${{ github.workspace }}

    - name: Build Frontend
      run: |
        npm run build
      working-directory: ${{ github.workspace }}

    - name: Deploy Frontend
      run: |
        mkdir -p ~/.ssh  # Ensure .ssh directory exists
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa  # Write private key
        chmod 600 ~/.ssh/id_rsa  # Set permissions
        ssh-keyscan -H 172.31.40.45 >> ~/.ssh/known_hosts  # Add server to known hosts
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@172.31.40.45 "sudo systemctl reload nginx"
